using JSON, SimilaritySearch, JLD2, DataFrames, LinearAlgebra

"""
    load_sentence_embeddings(filename; key, normalize)

Loads a sentence embeddings in h5 format, e.g., generated by `encode-file.py`.
"""
function load_sentence_embeddings(filename; key, normalize)
    jldopen(filename) do f
        X = f[key]
        if normalize
            for c in eachcol(X)
                normalize!(c)
            end
        end

        X
    end
end

"""
    knngraph(dist::SemiMetric, input::String; output::String, k::Int=16, minrecall::Float64=0.95, normalize=true, key::String="emb")

Computes an approximation of the ``k`` nearest neighbor graph

- `dist`: Distance function
- `input`: input embedding file (h5 format)
- `output`: filename to save the knn graph (using two matrices `knns` and `dists` of identifiers and distances)
- `k`: the number of neighbors 
- `minrecall`: controls the quality of the approximation (between 0 and 1)
- `normalize`: true if the embeddings must be adjusted to have unitary norm
- `key`: the name of the dataset inside of the input file
    
"""
function knngraph(dist::SemiMetric, input::String; output::String, k::Int=16, minrecall::Float64=0.95, normalize=true, key::String="emb")
    X = load_sentence_embeddings(input; key, normalize)
    G = SearchGraph(; dist, db=MatrixDatabase(X))
    minrecall = MinRecall(minrecall)
    callbacks = SearchGraphCallbacks(minrecall)
    index!(G; callbacks)
    optimize!(G, minrecall)
    knns, dists = allknn(G, k)
    jldsave(output; knns, dists)
    knns, dists
end

"""
    distsample(dist::SemiMetric, input::String; output::String, n_samples::Int=0, normalize=true, key::String="emb")
    
Computes a sample of size `n_samples` of the pairwise distance matrix

- `dist`: Distance function
- `input`: input embedding file (h5 format)
- `output`: filename to save the sample
- `prob`: sampling probability (on the upper triangle pairwise distance matrix)
- `normalize`: true if the embeddings must be adjusted to have unitary norm
- `key`: the name of the dataset inside of the input file
"""
function distsample(dist::SemiMetric, input::String; output::String, prob::Float64=0.1, key::String="emb", normalize::Bool=true)
    X = load_sentence_embeddings(input; key, normalize) |> MatrixDatabase
    n = length(X)
    S = Float32[]
    sizehint!(S, ceil(Int, prob * n))

    for i in 1:n
        for j in i+1:n-1
            if rand() <= prob
                push!(S, evaluate(dist, X[i], X[j]))
            end
        end
    end
   
    sort!(S)
    jldsave(output; dists=S)
    S  
end

    #=
        D = DataFrame(JSON.parse.(eachline("datasets/comp2023/IberLEF2023_HOMO-MEX_Es_train.json")))
D = DataFrame(JSON.parse.(eachline("datasets/comp2023/IberLEF2023_HOMO-MEX_Es_train.json")))

        for r in eachrow(D[knns[:, 1], :])
            println(r)
        end
# time: 2023-09-01 12:31:51 CST
# mode: julia
        for r in eachrow(D[knns[:, 1], :])
            println(r.klass => r.text)
        end
# time: 2023-09-01 12:36:19 CST
# mode: julia
        for r in eachrow(D[knns[:, 2], :])
            println(r.klass => r.text)
        end
        =#
